services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kamerreserveringbackend-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - kamerreservering_h2_data:/app/data
      - kamerreservering_uploads:/app/uploads

volumes:
  kamerreservering_h2_data:
  kamerreservering_uploads:
